name: Sync SMEXI-GitLab to GitHub

on:
  schedule:
    - cron: '0 0 * * *'  # Adjust the cron schedule as needed (this runs hourly)

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'akhilyeerasam'
          git config --global user.email 'actions@github.com'

      - name: Clone GitLab repository
        run: |
          git clone https://$DFKI_GITLAB_TOKEN@$DFKI_GITLAB_REPO gitlab-repo
          cd gitlab-repo
          git pull origin main  # Change 'main' if your branch is different
          cp -r * ../  # Copy files to the GitHub repository
          cd ..

      - name: Add and commit changes
        run: |
          git add .
          git commit -m "Sync from GitLab SMEXI" || echo "No changes to commit"

      - name: Push changes to GitHub
        run: |
          git push https://$GITHUB_TOKEN@github.com/${{ github.repository }} HEAD:main
