name: Sync SMEXI-GitLab to GitHub

on:
  schedule:
    - cron: '0 0 1,15 * *'  # Adjust the cron schedule as needed (this runs hourly)
  workflow_dispatch:  # Allows manual triggering of the workflow.

permissions:
  contents: write  # Grants write permission to the GitHub Actions bot

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.name 'akhilyeerasam'
          git config user.email 'actions@github.com'

      - name: Clone GitLab repository
        run: |
          git clone https://${{ secrets.DFKI_GITLAB_TOKEN }}@git.opendfki.de/sds-public/smexi.git gitlab-repo
          cd gitlab-repo
          git pull origin main  # Change 'main' if your branch is different
          cp -r * ../  # Copy files to the GitHub repository
          cd ..

      - name: Add and commit changes
        run: |
          git add --all
          git commit -m "Sync from GitLab SMEXI" || echo "No changes to commit"

      - name: Push changes to GitHub
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git push https://x-access-token:${{ secrets.MY_GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
